version: '2.2'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3001"  
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./websiteIpnu/logs:/app/logs
      - /opt/prod-stack/data/logs:/app/system-logs  
    networks:
      - prod-network

networks:
  prod-network:
    external: true 